services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  web:
    build: .
    command: >
      bash -c "
        while ! nc -z db 5432; do
          echo 'Waiting for database...';
          sleep 1;
        done;
        bundle exec rails db:migrate &&
        bundle exec rails db:seed &&
        bundle exec rails s -b 0.0.0.0 -p 3001
      "
    volumes:
      - ".:/app"
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключаем конфигурацию Nginx
    ports:
      - "80:80"  # Nginx будет слушать HTTP-запросы на порту 80
    networks:
      - mynetwork

volumes:
  data:

networks:
  mynetwork:
    driver: bridge

